# Generated by Django 3.1.5 on 2021-01-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210121_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'DELIVERY'), (3, 'DONE')], default=0),
        ),
    ]
