# Generated by Django 3.1.5 on 2021-01-21 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created',
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 9, 28, 15, 2281, tzinfo=utc)),
        ),
    ]
