# Generated by Django 3.1.5 on 2021-01-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20210121_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
