# Generated by Django 3.1.5 on 2021-01-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210121_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('status', '-created')},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'DELIVERY'), (3, 'DONE')], default=0),
        ),
    ]
