# Generated by Django 3.1.5 on 2021-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210121_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='customer',
            new_name='order',
        ),
    ]
