# Generated by Django 3.1.5 on 2021-01-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name_plural': 'All products'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('category',), 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AddField(
            model_name='product',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
