# Generated by Django 3.1.5 on 2021-01-19 10:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210106_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[420, 420], upload_to='products/%y/%m/%d'),
        ),
    ]
