# Generated by Django 3.1.5 on 2021-01-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210120_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated', 'name'), 'verbose_name_plural': 'All products'},
        ),
    ]
